const actionTypes = {
    LOGIN_USER: 'auth/LOGIN_USER',
    LOGIN_USER_FAILURE: 'auth/LOGIN_USER_FAILURE',
    LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',

    STILL_LOGGED_IN_USER: 'auth/STILL_LOGGED_IN_USER',

    VERIFY_LOGGED_IN_USER: 'auth/VERIFY_LOGGED_IN_USER',
    VERIFY_LOGGED_IN_USER_SUCCESS: 'auth/VERIFY_LOGGED_IN_USER_SUCCESS',
    VERIFY_LOGGED_IN_USER_FAILURE: 'auth/VERIFY_LOGGED_IN_USER_FAILURE',

    LOGOUT_USER: 'auth/LOGOUT_USER',
};

export default actionTypes;
